language: php

notifications:
  on_success: never
  on_failure: change

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=4.3-RC1 WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=0

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
